export const LIKE_EVENT = {
    LIKE: 1,
    UNLIKE: 2,
};
export const CASHBACK_WALKING_FIRSTTIME_GRANTED_PERMISSION =
    'CASHBACK_WALKING_FIRSTTIME_GRANTED_PERMISSION';
export const CASHBACK_WALKING_FIRSTTIME_SHOWED_INTRO = 'CASHBACK_WALKING_FIRSTTIME_SHOWED_INTRO';
export const WALKING_GRANTED_PERMISSION_EVENT = 'WALKING_GRANTED_PERMISSION_EVENT';
export const CONTACT_GRANTED_PERMISSION_EVENT = 'CONTACT_GRANTED_PERMISSION_EVENT';
export const WALKING_ERROR_EVENT = 'WALKING_ERROR_EVENT';
export const WALKING_JOINED_EVENT = 'WALKING_JOINED_EVENT';

export const NOTI_RECEIVE_WALKING_BADGES = 'NOTI_RECEIVE_WALKING_BADGES';

export const WALKING_INFO_MSG_V3 = 'WALKING_INFO_MSG_V3';
export const USER_TARGET_BY_STATISTICAL_DATE_WALKING = 'USER_TARGET_BY_STATISTICAL_DATE_WALKING';
export const STATISTICAL_USER_WALKING = 'STATISTICAL_USER_WALKING';
export const TAB_CHART_SELECTED = 'TAB_CHART_SELECTED';
