import { LocalizedStrings } from '@momo-platform/component-kits';

const Strings = new LocalizedStrings({
    vi: {
        goldenBoardTitle: 'Bảng vàng đi bộ',
        titleRanking: 'Bảng xếp hạng MoMo',
        titleWalking: 'Đi bộ cùng MoMo',
        shareAchievements: 'Chia sẻ Thành tích',
        joinWithMoMo: 'Tham gia cùng MoMo',
        numberPeopleWalking: 'Số người tham gia đi bộ',
        totalYourWalking: 'Tổng số bước của bạn nằm ở khoảng này',
        totalYourWalkingPermission: 'Tổng số bước của bạn nằm ở khoảng này (cần cấp quyền)',
        yourSteps: 'Số bước đi của bạn',
        thisWeek: 'Tuần này',
        lastWeek: 'Tuần trước',
        thisMonth: 'Tháng này',
        lastMonth: 'Tháng trước',
        grantAcessYourStepsData: 'Cho phép truy cập dữ liệu bước chân để theo dõi sức khoẻ của bạn',
        foodBagFull: 'Túi thức ăn đã đầy',
        foodBagFullDesc:
            'Túi thức ăn của Heo Đất không thể chứa thêm được, cho heo ăn xong hẵn quay lại nhận thức ăn nhé!',
        close: 'Đóng',
        feedThePig: 'CHO HEO ĂN',
        foodBagSoonFull: 'Túi thức ăn sắp đầy',
        foodBagSoonFullDesc:
            'Hiện tại, túi thức ăn chỉ có thể chứa thêm %@ gram thức ăn, bạn có muốn tiếp tục nhận?',
        take: 'Nhận',
        received: 'Đã nhận',
        changeGoldenPig: 'Đổi heo vàng',
        steps: 'bước',
        notFoundResult: 'Không tìm thấy kết quả',
        walkingPermission: 'Hãy đồng bộ dữ liệu bước chân để theo dõi sức khoẻ của bạn',
        walkingMomoPermission:
            'Hãy đồng bộ dữ liệu bước chân với MoMo để ghi lại kết quả của mình nhé',
        walkingPermissionIntro:
            'Đi bộ cùng MoMo là tính năng được tạo ra nhằm khuyến khích người dùng cải thiện sức khỏe',
        walkingPermissionIntroContent: 'Tham gia cùng bạn bè để tăng thêm niềm vui',
        walkingPermissionDesc: 'MoMo cần sự cho phép của bạn để có thể đếm bước chân',
        walkingPermissionIOSAuth1: 'Chọn "Turn All Categories On“ hoặc mở Step',
        walkingPermissionIOSAuth2: 'Ấn "Allow” và bạn đã tham gia chương trình',
        walkingPermissionIOSAuth3:
            'Chọn "Turn All Categories On“ hoặc mở Step & trở về ứng dụng MoMo',
        walkingPermissionIOSAuthHeath: 'Từ ứng dụng Health, ấn chọn tab Source',
        chosseMoMoApp: 'Chọn ứng dụng MoMo',
        walkingPermissionAndroidAuth1: 'Chọn tài khoản Google của bạn',
        walkingPermissionAndroidAuth2: 'Ấn “Allow” và bạn đã tham gia chương trình',
        access: 'TRUY CẬP',
        continue: 'TIẾP TỤC',
        back: 'QUAY LẠI',
        walkingPermissionError: 'Thiết bị không hỗ trợ chức năng này!',
        cashbackEmptyMessage: 'Bạn chưa có danh sách bạn bè, thêm bạn để cùng đi mỗi ngày',
        findFriendInContact: 'Tìm bạn bè từ danh bạ',
        loadingMessage: 'Danh sách bạn bè đang được cập nhật, vui lòng chờ...',
        youGetFood: 'Nhận được thức ăn từ chương trình',
        confirm: 'Xác nhận',
        change: 'Quy đổi',
        youWantChange: 'Bạn muốn đổi',
        goldenPig: 'heo vàng',
        cashbackHealthMessage: 'Bạn không có đủ huy hiệu sức khoẻ',
        cashbackEmptyMessageChange: 'Để đổi %@ heo vàng, bạn sẽ dùng %@ huy hiệu sức khỏe',
        agree: 'Đồng ý',
        cancel: 'Huỷ',
        updateNew: 'Cập nhật mới',
        discoverNow: 'Khám phá ngay',
        listRankingLoading: 'Danh sách bảng xếp hạng đang được cập nhật…',
        congratulations: 'Chúc mừng',
        WalkingCollectMessage: 'Bạn đã quy đổi thành công 1 heo vàng',
        donateNow: 'Quyên góp ngay',
        donate: 'Quyên góp',
        stepHasGone: 'Bước đã đi',
        goalReceived: 'Mục tiêu đã nhận',
        totalBadge: 'Tổng huy hiệu',
        heartReceived: 'Tim đã nhận',
        cashbackWalkingStaticMessage:
            '* Các thông tin trên được ghi nhận từ lúc bạn tham gia đi bộ cùng MoMo.',
        ranking: 'Bảng xếp hạng',
        rankingMoMo: 'Bảng xếp hạng MoMo',
        rankingSectionInTop:
            '<p>Bạn đã đi %@ bước trong tuần này, bạn đang nằm trong top những người dẫn đầu</p>',
        rankingSectionPermission:
            '<p>Hãy cấp quyền truy cập để xem thành tích của bạn so với người dùng MoMo</p>',
        walkingEmptyMessage: 'nhahưa có kết quả,bấmđi bộ để cập nhật',
        research: 'Tìm hiểu',
        intro: 'Giới thiệu',
        contactPermission: 'Hãy đồng bộ danh bạ để đi bộ cùng với bạn bè',
        walkingRankingMoMoMessage: 'Bạn đã đi được %@ bước, cao hơn %@ người dùng MoMo',
        walkingRankingMoMoMessage1:
            '<p>Tổng số bước bạn đi khá nhiều, đi bộ nhiều hơn để lọt vào top có thành tích cao nhé!</p>',
        walkingRankingMoMoMessage2:
            '<p>Vì sức khoẻ của bản thân, hãy đi bộ nhiều hơn cùng MoMo</p>',
        walkingRankingMoMoMessage3:
            '<p>Bạn đã đi được <b>%@</b> bước, bạn đang nằm trong nhóm những người dẫn đầu</p>',
        walkingRankingMoMoPermission:
            '<p>Cùng MoMo tìm hiểu trong tuần hay tháng qua bạn đã đi bộ được bao nhiêu?</p>',
        walkingRankingLoading: 'Dữ liệu đang được tải ...',
        notification: 'Thông báo',
        visitPig: 'Thăm Heo',
        UnableToWithdrawPig: 'Chưa thể rút heo',
        needBankingInformation:
            '<p>Theo quy định của Ngân hàng nhà nước, để sử dụng Ví điện tử, bạn cần thêm thông tin ngân hàng, thẻ ATM nội địa hoặc thẻ ghi nợ Visa/Mastercard/JCB</p>',
        later: 'Để Sau',
        addNow: 'Thêm Ngay',
        systemUpgrade: 'Hệ thống đang được nâng cấp, quý khách vui lòng thử lại sau ít phút nhé.',
        skip: 'Bỏ qua',
        callMoMo: 'Liên hệ MoMo',
        share: 'Chia sẻ',
        shareMessage: 'Nào mình cùng MoMo nhé!',
        sync: 'Đồng bộ',
        day: 'Ngày',
        days: 'Ngày',
        week: 'Tuần',
        month: 'Tháng',
        allow: 'Cho phép',
        challengeWithFriends: 'Thử thách cùng bạn bè',
        contactPermissionFirst: 'Cho phép truy cập danh bạ để theo dõi và chia sẻ cùng với bạn bè.',
        momoError: 'Chờ MoMo nghỉ uống nước xíu, lát bạn quay lại nha!',
        comingSoon: 'Sắp diễn ra',
        eventEnded: 'Đã kết thúc',
        firstPersonToJoin: 'Hãy là người đầu tiên tham gia sự kiện này',
        groupRanking: 'Bảng xếp hạng đội',
        eventInfo: 'Thông tin chương trình',
        seeMore: 'Xem thêm',
        closeUp: 'Đóng lại',
        seenAll: 'Bạn đã xem hết rồi!',
        startInstruction: 'Bạn hãy bấm bắt đầu và thực hiện theo hướng dẫn trên',
        start: 'Bắt đầu',
        seeAll: 'Xem tất cả',
        recentBadges: 'Danh hiệu gần đây',
        joinSuccess: 'Tham gia thành công',
        beforeBegin: 'Trước khi bắt đầu',
        detail: 'Chi tiết',
        join: 'Tham gia',
        noMonthData: 'Chưa có dữ liệu tháng này',
        noTodayData: 'Chưa có dữ liệu hôm nay',
        rankingMonth: 'Bảng xếp hạng tháng này',
        shareNow: 'Chia sẻ ngay',
        dayRecord: 'Kỉ lục ngày',
        weekRecord: 'Kỉ lục tuần',
        monthRecord: 'Kỉ lục tháng',
        individualRanking: 'Bảng xếp hạng cá nhân',
        eventDetail: 'Chi tiết sự kiện',
        confirmGroupTitle: 'Xác nhận tham gia đội',
        confirmGroupDesc:
            'Bạn đang tham gia đội @, số bước chân trong sự kiện của bạn sẽ chỉ được tính cho đội này. Bạn không thể thay đổi đội trong sự kiện.',
        confirmJoin: 'Đồng ý',
        confirmCancel: 'Huỷ bỏ',
        joinEventSuccess: 'Tham gia thành công!',
        joinEventDesc: 'Hãy bắt đầu đi bộ và duy trì mỗi ngày để sớm đạt mục tiêu bạn nhé!',
        beforeStart: 'Trước khi bắt đầu',
        pleaseSync: 'Hãy đồng bộ bước chân với MoMo để ghi lại kết quả của mình nhé',
        chooseTeam: 'Bạn vui lòng chọn đội để tham gia nhé',
        chooseTeamToJoin: 'Để tham gia, hãy chọn đội của bạn nhé',
        syncAfterEvent: 'Dữ liệu bước chân sẽ được cập nhật sau khi sự kiện bắt đầu',
        syncFriend: 'Hãy đồng bộ danh bạ để đi bộ cùng bạn bè',
        friendNoData: 'Chưa có dữ liệu bước chân của bạn bè',
        noDataEvent: 'Chưa có dữ liệu bước chân của sự kiện này',
        joinNow: 'Đăng ký ngay!',
        endSoon: 'Chương trình kết thúc sau: ',
        startSoon: 'Chương trình sẽ bắt đầu sau: ',
        teamDetail: 'Chi tiết đội',
        badge: 'danh hiệu',
        collected: 'Đã sưu tập được',
        friends: 'Bạn bè',
        today: 'Hôm nay',
        updatingEventInfo: 'Thông tin chương trình đang được cập nhật...',
        collection: 'Bộ sưu tập',
        noEventInfo: 'Không tìm thấy thông tin sự kiện.',
        chooseYourTeam: 'Chọn đội tham gia',
        hour: 'Giờ',
        hours: 'Giờ',
        minute: 'Phút',
        minutes: 'Phút',
        second: 'Giây',
        seconds: 'Giây',
        reached: 'Đã đạt',
        step: 'bước chân',
        members: 'thành viên',
    },
    en: {
        goldenBoardTitle: 'Leaderboard',
        titleRanking: 'MoMo Ranking',
        titleWalking: 'Walking with MoMo',
        shareAchievements: 'Share Achievements',
        joinWithMoMo: 'Join with MoMo',
        numberPeopleWalking: 'Total people join',
        totalYourWalking: 'Your total steps are about',
        totalYourWalkingPermission: 'Your total steps are about (need permission)',
        yourSteps: 'Your steps',
        thisWeek: 'This week',
        lastWeek: 'Last week',
        thisMonth: 'This month',
        lastMonth: 'Last month',
        grantAcessYourStepsData: 'Please grant permission to sync your steps to check your health',
        foodBagFull: 'Food bag is full',
        foodBagFullDesc:
            'The food bad is full! Please feed the pig and then come back for more food!',
        close: 'Close',
        feedThePig: 'FEED THE PIG',
        foodBagSoonFull: 'Food bad is full soon',
        foodBagSoonFullDesc:
            'Currently, food bad can only take %@ grams of food, do you wish to proceed?',
        take: 'Take',
        received: 'Received',
        changeGoldenPig: 'Change golden pig',
        steps: 'steps',
        notFoundResult: 'Results not found',
        walkingPermission: 'Please sync your steps to check your health',
        walkingMomoPermission: 'Please sync your steps to keep your record',
        walkingPermissionIntro:
            'Walking with MoMo is created to encourage people to improve their health',
        walkingPermissionIntroContent: 'Join with friends! The more the merrier!',
        walkingPermissionDesc: 'MoMo needs your permission to sync your steps',
        walkingPermissionIOSAuth1: 'Choose "Turn All Categories On" or open Step',
        walkingPermissionIOSAuth2: 'Press "Allow" and you\'re in!',
        walkingPermissionIOSAuth3:
            'Choose "Turn All Categories On" or open Step & go back to MoMo App',
        walkingPermissionIOSAuthHeath: 'From Health, choose Source tab',
        chosseMoMoApp: 'Choose MoMo App',
        walkingPermissionAndroidAuth1: 'Choose your Google account',
        walkingPermissionAndroidAuth2: 'Press "Allow" and you\'re in!',
        access: 'JOIN',
        continue: 'CONTINUE',
        back: 'BACK',
        walkingPermissionError: 'Device is not supported!',
        cashbackEmptyMessage: "You don't have friend list, add more to compete with them",
        findFriendInContact: 'Find friends from contact',
        loadingMessage: 'Updating friend list, please wait...',
        youGetFood: 'You have received food from the event',
        confirm: 'Confirm',
        change: 'Exchange',
        youWantChange: 'Do you want to change',
        goldenPig: 'golden pig',
        cashbackHealthMessage: "You don't have any health badges",
        cashbackEmptyMessageChange:
            'To exchange %@ golden pigs, you need to convert %@ health badges',
        agree: 'Agree',
        cancel: 'Cancel',
        updateNew: 'New update',
        discoverNow: 'Explore now',
        listRankingLoading: 'Updating leaderboard...',
        congratulations: 'Congratulations',
        WalkingCollectMessage: 'One golden pig has been exchanged successfully',
        donateNow: 'Donate now',
        donate: 'Donate',
        stepHasGone: 'Your steps',
        goalReceived: 'Your achieved goals',
        totalBadge: 'Badges achievement',
        heartReceived: 'Received hearts',
        cashbackWalkingStaticMessage:
            '* The above information has been collected since you started walking with MoMo.',
        ranking: 'Ranking',
        rankingMoMo: 'MoMo Leaderboard',
        rankingSectionInTop:
            '<p>You have taken %@ steps this week, you are in the top of the group</p>',
        rankingSectionPermission: "<p>Please grant permission to find out MoMo's users ranking</p>",
        walkingEmptyMessage: 'The result is empty, press Walking to update',
        research: 'More info',
        intro: 'Introduction',
        contactPermission: 'Please grant your contact permission to enjoy walk with your friends',
        walkingRankingMoMoMessage:
            'You have taken %@ steps, which is %@ higher than other MoMo users',
        walkingRankingMoMoMessage1:
            '<p>You have done a great job! Walk more to achieve higher place on the ranking</p>',
        walkingRankingMoMoMessage2:
            '<p>Walking with MoMo more frequently to enhance your health</p>',
        walkingRankingMoMoMessage3:
            '<p>You have taken <b>%@</b> steps, you are in the top of the group</p>',
        walkingRankingMoMoPermission:
            "<p> Let's see how many steps you took last month, shall we?</p>",
        walkingRankingLoading: 'Downloading data ...',
        notification: 'Information',
        visitPig: 'Visit Pig',
        UnableToWithdrawPig: 'Unable to withdraw the pig',
        needBankingInformation:
            '<p>As the Government claimed, you need to provide bank information, ATM or Visa/Mastercard/JCB Debit Card to use e-Wallet</p>',
        later: 'Maybe later',
        addNow: 'Add now',
        systemUpgrade: 'The system is under maintenance. Please try again in a few minutes.',
        skip: 'Skip',
        callMoMo: 'Contact MoMo',
        share: 'Share',
        shareMessage: "Let's join MoMo",
        sync: 'Sync',
        day: 'Day',
        days: 'Days',
        week: 'Week',
        month: 'Month',
        allow: 'Allow',
        challengeWithFriends: 'Challenge with friends',
        contactPermissionFirst: 'Please sync contact to join with friends',
        momoError: 'I need some water! Please come back later!',
        comingSoon: 'Coming soon',
        eventEnded: 'Ended',
        firstPersonToJoin: 'Be the first to join this event',
        groupRanking: 'Team ranking',
        eventInfo: 'Event information',
        seeMore: 'See more',
        closeUp: 'Close',
        seenAll: 'This is the end of the page!',
        startInstruction: 'Please press start and follow the instructions',
        start: 'Start',
        seeAll: 'See all',
        recentBadges: 'Recent badges',
        joinSuccess: 'Joined successfully',
        beforeBegin: 'Before starting',
        detail: 'Detail',
        join: 'Join',
        noMonthData: 'No data for this month',
        noTodayData: 'No data for today',
        rankingMonth: 'Monthly ranking',
        shareNow: 'Share now',
        dayRecord: 'Day record',
        weekRecord: 'Week record',
        monthRecord: 'Month record',
        individualRanking: 'Personal ranking',
        eventDetail: 'Event details',
        confirmGroupTitle: 'Confirm joining this team',
        confirmGroupDesc:
            'You are joining @, your steps in this event will be counted for this team only. You cannot change the team during the event.',
        confirmJoin: 'Confirm',
        confirmCancel: 'Cancel',
        joinEventSuccess: 'Successfully joined this event!',
        joinEventDesc: 'Keep on walking everyday to reach your record soon!',
        beforeStart: 'Before starting',
        pleaseSync: 'Please sync your step to keep your record',
        chooseTeam: 'Please choose a team to join',
        chooseTeamToJoin: 'Please choose a team to join',
        syncAfterEvent: 'Steps data will be synced after the event starts',
        syncFriend: 'Please sync your contact to compete with friends',
        friendNoData: 'No steps data of friends',
        noDataEvent: 'No steps data for this event',
        joinNow: 'Join now!',
        endSoon: 'The event will end in: ',
        startSoon: 'The event will start in: ',
        teamDetail: 'Team detail',
        badge: 'badges',
        collected: 'Collected',
        friends: 'Friends',
        today: 'Today',
        updatingEventInfo: 'Event information is updating...',
        collection: 'Collection',
        noEventInfo: 'Cannot find event information.',
        chooseYourTeam: 'Choose your team',
        hour: 'Hour',
        hours: 'Hours',
        minute: 'Minute',
        minutes: 'Minutes',
        second: 'Second',
        seconds: 'Seconds',
        reached: 'Reached',
        step: 'steps',
        members: 'members',
    },
});

export default Strings;
